development:
  email_provider_username: <%= ENV["email"] %>
  email_provider_password: <%= ENV["password"] %>
  mailchimp_api_key: <%= ENV["e38ead8b9150dfeaefee599e6b065372-us3"] %>
  mailchimp_list_id: <%= ENV["a53f20afe8"] %>
  domain_name: gmail.com
  owner_email: <%= ENV["owner_email"] %>
  secret_key_base: <%= ["SECRET_KEY_BASE"]%>

test:
  secret_key_base: <%= ["SECRET_KEY_BASE"]%>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["email"] %>
  email_provider_password: <%= ENV["password"] %>
  mailchimp_api_key: <%= ENV["e38ead8b9150dfeaefee599e6b065372-us3"] %>
  mailchimp_list_id: <%= ENV["a53f20afe8"] %>
  domain_name: gmail.com
  owner_email: <%= ENV["owner_email"] %>
  secret_key_base: <%= ["SECRET_KEY_BASE"]%>




#development:
 # secret_key_base: f4ad19b4ae7bb020f0b77bfb3515c34d60acfbc3f42c40bb84c57443ce578c03f156c07a932ed1fa09b96b97a62e7578ad7b1aed71af5e887a346046b533877a

#test:
 # secret_key_base: aff57fb347ddd519756ed7e2d14334bddfd7f0323a6e461dbb0993f23f55c51172caf4dc9f04da5e00e412565578d38ec9fc9e0fc381215c8bf5cab9555f60ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
